name: Ai exercieses

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v4

    - name: set up java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make maven wrapper runnable
      run: chmod +x ./mvnw
    - name:
      run: ./mvnw test