name: Exercies-one

on: push

jobs:
   exercises-1:
    runs-on: ubuntu-latest
    steps:
      - name: Excercies-One
        uses: actions/checkout@v4
      - name: Set-up java
        uses: actions/setup-java@v5
        with:
          version: '21'
          distribution: 'temurin'
      - name: make Maven wrapper runnable
        run: chmod +x
      - name: Run java
        run: ./mvnw clean install