name: Exercies-one

on: push

jobs:
   exercises-1:
    runs-on: ubuntu-latest
    steps:
      - name: Excercies-One
        uses: actions/checkout@v5
      - name: Set-up java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: make Maven wrapper runnable
        run: chmod +x ./mvnw
      - name: Run java
        run: ./mvnw clean install
      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Sunfire-reports
          path: target/surefire-reports/
          if-no-file: warn