name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'turmin'
          cache: maven
      - name: Run tests
        run: mvn test
